# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKgdfzjhUAE_D4ngNy_Ua-oLKsZCW4_n

## **Preprocessing for Coffee, Lifestyle & Sleep EDA notebook and Streamlit application**

#### **Install libraries**
"""

import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype

"""#### **Convert data**"""

# Convert data

def convert_categorical(data, features):
  '''
  Convert nominal features into categories.
  data: DataFrame
  features: List of nominal features
  '''

  for feature in features:
    data[feature] = data[feature].astype('category')

  return data

def convert_ordinal(data, feature_dict):
  '''
  Convert ordinal features into categories.
  data: DataFrame
  feature_dict: Dictionary of ordinal features and categories
                {'feature': ['sub-category1', 'sub-category2']}
  '''

  for feature, subcategories in feature_dict.items():
    if data[feature].dtype.name == 'category':
      continue
    ordinal = CategoricalDtype(categories = subcategories, ordered = True)
    data[feature] = data[feature].astype(ordinal)

  return data

"""#### **Group data**"""

def mean_data(data, feature, target):
  '''
  Calculate the mean data based on groupby variable and variable of interest.
  data: Dataframe
  feature: str groupby variable
  target: str variable of interest
  '''

  df = (data
        .groupby(feature, observed = False)[target]
        .mean()
        .reset_index())

  return df

"""### **Streamlit application**

#### **Clean data**
"""

def clean_data(df):
  '''
  Clean the Kaggle coffee dataset.
  df: DataFrame
  '''

  df = df.copy()

  # Clean columns
  df.columns = df.columns.str.replace('_', ' ')

  # Fill missing values with None per data dictionary
  df['Health Issues'] = df['Health Issues'].fillna('None')

  return df

def filter_caffeine(df):
  '''
  Filter out individuals who consume caffeine but do not have recorded coffee intake.
  df: DataFrame
  '''

  df = df.copy()

  # Consume caffeine but not coffee
  caffeine_drinkers = df[(df['Coffee Intake'] == 0.0) & (df['Caffeine mg'] > 0.0)]

  # Drop rows
  df_coffee = df.drop(caffeine_drinkers.index)

  return df_coffee

def engineer_features(df, binary_feat, nominal_feat, ordinal_dict):
  '''
  Engineer features for coffee dataset.
  df_coffee: DataFrame
  binary_feat: List of binary features
  nominal_feat: List of nominal features
  ordinal_dict: Dictionary of ordinal features and categories
  '''

  df = df.copy()

  # Create coffee binary feature: whether individual consumes coffee (1) or not (0):
  df['Coffee'] = (df['Coffee Intake'] > 0).astype(int)

  # Creating ordinal variables for age and physical activity hours
  df['Ages'] = pd.cut(df['Age'],
                      bins = [-np.inf, 24, 34, 44, 54, 64, np.inf],
                      labels = ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'])
  df['Lifestyle'] = pd.cut(df['Physical Activity Hours'],
                           bins = [-np.inf, 2.5, 5, 7.5, np.inf],
                           labels = ['Sedentary', 'Standard', 'Active', 'Highly Active'])

  df_coffee = (df
               .pipe(convert_categorical, binary_feat + nominal_feat)
               .pipe(convert_ordinal, ordinal_dict))

  return df_coffee